# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180220_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(default='h'),
            preserve_default=False,
        ),
    ]
